# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
"""Workload spec builder."""
from __future__ import absolute_import

import json
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from sagemaker.serve.ai_inference_recommender.secrets import Secret


# Logical name used for the dataset channel when the caller doesn't
# specify one. Visible to the customer only as the directory under
# /opt/ml/input/data/ where the S3 contents are mounted; not part of any
# API contract that customers should rely on.
_DEFAULT_CHANNEL_NAME = "dataset"


class _DatasetChannel(BaseModel):
    """Internal record of an S3 channel that should be mounted at job runtime.

    Used by ``Workload.from_dataset`` to capture the S3 URI and channel name
    so :class:`AIWorkloadConfig` can be created with the matching
    ``DatasetConfig``. AIPerf reads the dataset from the container path
    declared in ``parameters.input_file``; this record exists only to plumb
    the S3-side configuration through to the service.
    """

    channel_name: str
    s3_uri: str


class Workload(BaseModel):
    """A workload specification used by benchmark and recommendation jobs."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    parameters: Dict[str, Any]
    secrets: Dict[str, Union[str, Secret]] = Field(default_factory=dict)
    tooling: Dict[str, Any] = Field(default_factory=lambda: {"api_standard": "openai"})
    dataset_channels: List[_DatasetChannel] = Field(default_factory=list)

    @classmethod
    def synthetic(
        cls,
        *,
        tokenizer: str,
        concurrency: int = 1,
        request_count: int = 100,
        prompt_input_tokens_mean: int = 256,
        prompt_input_tokens_stddev: float = 0.0,
        output_tokens_mean: int = 256,
        output_tokens_stddev: float = 0.0,
        streaming: bool = True,
        hf_token: Optional[Union[str, Secret]] = None,
        **params: Any,
    ) -> "Workload":
        """Build a workload that uses synthetic prompts.

        Synthetic prompts are generated by AIPerf from the Sonnet dataset,
        producing realistic token distributions. Use
        :meth:`Workload.from_dataset` to drive the benchmark from a real
        request trace instead.

        Args:
            tokenizer: HuggingFace tokenizer id (e.g. ``meta-llama/Llama-3.2-1B``).
            concurrency: Number of in-flight requests.
            request_count: Total number of requests to issue.
            prompt_input_tokens_mean: Mean input prompt length in tokens.
            prompt_input_tokens_stddev: Standard deviation of input token count.
            output_tokens_mean: Mean output response length in tokens.
            output_tokens_stddev: Standard deviation of output token count.
            streaming: Whether to use streaming chat completions.
            hf_token: HuggingFace access token for gated tokenizers. Accepts a
                ``Secret`` or a Secrets Manager ARN string.
            **params: Additional parameters merged into the workload's
                ``parameters`` map.
        """
        parameters: Dict[str, Any] = {
            "tokenizer": tokenizer,
            "concurrency": concurrency,
            "request_count": request_count,
            "prompt_input_tokens_mean": prompt_input_tokens_mean,
            "prompt_input_tokens_stddev": prompt_input_tokens_stddev,
            "output_tokens_mean": output_tokens_mean,
            "output_tokens_stddev": output_tokens_stddev,
            "streaming": streaming,
            **params,
        }
        secrets: Dict[str, Union[str, Secret]] = {}
        if hf_token is not None:
            secrets["hf_token"] = hf_token
        return cls(parameters=parameters, secrets=secrets)

    @classmethod
    def sonnet(cls, **kwargs: Any) -> "Workload":
        """Alias for :meth:`synthetic`.

        AIPerf seeds synthetic prompts from the Sonnet dataset by default,
        so ``Workload.sonnet(...)`` is the same as ``Workload.synthetic(...)``.
        """
        return cls.synthetic(**kwargs)

    @classmethod
    def from_dataset(
        cls,
        s3_uri: str,
        *,
        custom_dataset_type: Optional[str] = None,
        tokenizer: Optional[str] = None,
        concurrency: int = 1,
        request_count: int = 100,
        prompt_input_tokens_mean: int = 256,
        prompt_input_tokens_stddev: float = 0.0,
        output_tokens_mean: int = 256,
        output_tokens_stddev: float = 0.0,
        streaming: bool = True,
        hf_token: Optional[Union[str, Secret]] = None,
        **params: Any,
    ) -> "Workload":
        """Build a workload that drives traffic from an S3-hosted dataset.

        The S3 prefix is mounted into the benchmark container by the
        SageMaker AI inference recommender service via the workload config's
        ``DatasetConfig``. AIPerf reads the file from the mounted directory.

        Args:
            s3_uri: ``s3://bucket/prefix/`` URI containing the dataset.
            custom_dataset_type: Optional AIPerf custom-dataset format
                (e.g. ``"openai-chat"``).
            tokenizer: Optional HuggingFace tokenizer id; required for some
                AIPerf metrics that compute per-token statistics.
            concurrency: Number of in-flight requests.
            request_count: Total number of requests to issue.
            prompt_input_tokens_mean: Mean input prompt length in tokens.
            prompt_input_tokens_stddev: Standard deviation of input token count.
            output_tokens_mean: Mean output response length in tokens.
            output_tokens_stddev: Standard deviation of output token count.
            streaming: Whether to use streaming chat completions.
            hf_token: HuggingFace access token for gated tokenizers. Accepts
                a ``Secret`` or a Secrets Manager ARN string.
            **params: Additional AIPerf parameters merged into the workload's
                ``parameters`` map. Use ``input_file=`` here to point at a
                specific file within the mounted prefix.

        Returns:
            A ``Workload`` whose ``dataset_channels`` carry the S3 URI for the
            service to mount.
        """
        if not s3_uri.startswith("s3://"):
            raise ValueError(
                f"s3_uri must start with 's3://'; got {s3_uri!r}."
            )
        parameters: Dict[str, Any] = {
            "concurrency": concurrency,
            "request_count": request_count,
            "prompt_input_tokens_mean": prompt_input_tokens_mean,
            "prompt_input_tokens_stddev": prompt_input_tokens_stddev,
            "output_tokens_mean": output_tokens_mean,
            "output_tokens_stddev": output_tokens_stddev,
            "streaming": streaming,
            **params,
        }
        if custom_dataset_type is not None:
            parameters["custom_dataset_type"] = custom_dataset_type
        if tokenizer is not None:
            parameters["tokenizer"] = tokenizer
        secrets: Dict[str, Union[str, Secret]] = {}
        if hf_token is not None:
            secrets["hf_token"] = hf_token
        return cls(
            parameters=parameters,
            secrets=secrets,
            dataset_channels=[
                _DatasetChannel(channel_name=_DEFAULT_CHANNEL_NAME, s3_uri=s3_uri),
            ],
        )

    def to_inline(self) -> str:
        """Serialize the workload to a JSON string.

        ``Secret`` values are flattened to their ARN strings.
        """
        flat_secrets = {
            k: (v.arn if isinstance(v, Secret) else v) for k, v in self.secrets.items()
        }
        payload: Dict[str, Any] = {
            "benchmark": {"type": "aiperf"},
            "parameters": self.parameters,
            "tooling": dict(self.tooling),
        }
        if flat_secrets:
            payload["secrets"] = flat_secrets
        return json.dumps(payload)
