#!/bin/sh
# this pre-push hook runs style checks and unit tests in python 3.8, 3.9, and 3.10 using tox.

set -e

TOX_PARALLEL_NO_SPINNER=1,
PY_COLORS=0
start_time=`date +%s`
tox -e flake8,pylint,docstyle,black-check,twine --parallel all
./ci-scripts/displaytime.sh 'flake8,pylint,docstyle,black-check,isort-check,twine' $start_time
start_time=`date +%s`
tox -e sphinx,doc8 --parallel all
./ci-scripts/displaytime.sh 'sphinx,doc8' $start_time
start_time=`date +%s`
tox -e py39,py310,py311,py312 --parallel all -- tests/unit
./ci-scripts/displaytime.sh 'py39,py310,py311,py312 unit' $start_time
