# ReadTheDocs environment customization to allow us to use conda to install
# libraries which have C dependencies for the doc build. See:
# https://docs.readthedocs.io/en/latest/config-file/v2.html

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"


python:
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt


sphinx:
  configuration: doc/conf.py
  fail_on_warning: true # http://www.sphinx-doc.org/en/master/man/sphinx-build.html#id6
