version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      - IGNORE_COVERAGE=-

      # local mode tests
      - start_time=`date +%s`
      - execute-command-if-has-matching-changes "tox -e py27,py36 -- tests/integ -m local_mode --durations 50" "tests/" "src/*.py" "setup.py" "setup.cfg" "buildspec-localmodetests.yml"
      - ./ci-scripts/displaytime.sh 'py27,py36 local mode' $start_time
