version: 0.2

phases:
  build:
    commands:
      # run notebook test
      - echo "running notebook test"
      - start_time=`date +%s`
      - HAS_MATCHING_CHANGES_OUTPUT=$(has-matching-changes "src/*.py" "setup.py" "setup.cfg" "tests/scripts/run-notebook-test.sh")
      - |
        if [ "$HAS_MATCHING_CHANGES" = "Changes Found" ] ; then
          ./tests/scripts/run-notebook-test.sh
        fi
      - ./ci-scripts/displaytime.sh 'notebook test' $start_time
