version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      # run linters
      - apt-get install time -y
      - time tox -e flake8,pylint
      - echo "======= FINISHED FLAKE8 ======="

      # run package and docbuild checks
      - time tox -e twine
      - echo "======= FINISHED TWINE ======="
      -
      - time tox -e sphinx
      - echo "======= FINISHED SPHINX ======="

      # run unit tests
      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
        time tox -e py36,py27 -- tests/unit
      - echo "======= FINISHED UNIT TESTS ======="
#
#      # run notebook test
#      - |
#        if has-matching-changes "src/*.py" "setup.py" "setup.cfg" "buildspec.yml"; then
#          echo "running notebook test"
#          ./tests/scripts/run-notebook-test.sh
#         else
#           echo "skipping notebook test"
#         fi

      # run integration tests
      - |
        if has-matching-changes "tests/" "src/*.py" "setup.py" "setup.cfg" "buildspec.yml"; then
          IGNORE_COVERAGE=- time tox -e py36,py27 -- tests/integ -n 62 --boxed --reruns 2
        else
          echo "skipping integration tests"
        fi
      - echo "======= FINISHED INTEGRATION TESTS ======="
