version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      - IGNORE_COVERAGE=-

      # local mode tests
      - start_time=`date +%s`
      - execute-command-if-has-matching-changes "tox -e py38 -- tests/integ -m local_mode --durations 50" "tests/integ" "tests/data" "tests/conftest.py" "tests/__init__.py" "src/*.py" "setup.py" "setup.cfg" "buildspec-localmodetests.yml"
      - ./ci-scripts/displaytime.sh 'py38 local mode' $start_time
