version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      - IGNORE_COVERAGE=-

      # run integration tests
      - start_time=`date +%s`
      - HAS_MATCHING_CHANGES_OUTPUT=$(has-matching-changes "tests/" "src/*.py" "setup.py" "setup.cfg" "buildspec.yml")
      - HAS_MATCHING_CHANGES_EXIT_CODE=$?
      - |
        if [ $HAS_MATCHING_CHANGES_EXIT_CODE -eq 1 ] ; then
          echo "There was an error checking for matching changes. PR will now fail to prevent false negative (success) tests."
          exit 1
        fi
        if [ $HAS_MATCHING_CHANGES -eq "Changes Found" ] ; then
          python3 -u ci-scripts/queue_build.py
        fi
      - ./ci-scripts/displaytime.sh 'build queue' $start_time

      - start_time=`date +%s`
      - |
        if [ $HAS_MATCHING_CHANGES -eq "Changes Found" ] ; then
          tox -e py36 -- tests/integ -m "not local_mode" -n 512 --reruns 3 --reruns-delay 5 --durations 50 --boto-config '{"region_name": "us-east-2"}'
        fi
      - ./ci-scripts/displaytime.sh 'py36 tests/integ' $start_time

  post_build:
    finally:
      - |
        if [ -d "ci-lock" ]; then
          FILENAME=$(ls ci-lock/ || true)
          ACCOUNT=$(aws --endpoint-url https://sts.us-west-2.amazonaws.com sts get-caller-identity --region us-west-2 --output text | awk '{print $1}')
          S3_BUCKET_DIR=s3://sagemaker-us-west-2-${ACCOUNT}/ci-lock/
          aws s3 rm ${S3_BUCKET_DIR}${FILENAME}
        fi
