version: 0.2

phases:
  build:
    commands:
      # run linters
      - tox -e flake8,pylint

      # run format verification
      - tox -e black-check

      # run package and docbuild checks
      - tox -e twine,sphinx,doc8

      # run unit tests
      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
        tox -e py36,py37,py38 -- tests/unit

      # run a subset of the integration tests
      - IGNORE_COVERAGE=- tox -e py36 -- tests/integ -m canary_quick -n 64 --boxed --reruns 2
