version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd
      - pip install boto3

  build:
    commands:
      - |
        python ci-scripts/queue_build.py
        sleep 20m

#      # run linters
#      - tox -e flake8,pylint
#
#      # run package and docbuild checks
#      - tox -e twine
#      - tox -e sphinx
#
#      # run format verification
#      - tox -e black-check
#
#      # run unit tests
#      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
#        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
#        tox -e py36,py27 -- tests/unit
#
#      # run notebook test
#      - |
#        if has-matching-changes "src/*.py" "setup.py" "setup.cfg" "buildspec.yml"; then
#          echo "running notebook test"
#          ./tests/scripts/run-notebook-test.sh
#         else
#           echo "skipping notebook test"
#         fi
#
#      # wait its turn to run integration tests
#      - ACCOUNT=$(aws sts get-caller-identity --output text | awk '{print $1}')
#      - S3_BUCKET_DIR=s3://sagemaker-us-west-2-${ACCOUNT}/ci-lock
#
#      # run integration tests
#      - |
#        if has-matching-changes "tests/" "src/*.py" "setup.py" "setup.cfg" "buildspec.yml"; then
#          python ci/queue_build.py
#          IGNORE_COVERAGE=- tox -e py36,py27 -- tests/integ -n 24 --boxed --reruns 2
#        else
#          echo "skipping integration tests"
#        fi
    finally:
      - FILENAME=$(ls ci-lock/)
      - ACCOUNT=$(aws sts get-caller-identity --output text | awk '{print $1}')
      - S3_BUCKET_DIR=s3://sagemaker-us-west-2-${ACCOUNT}/ci-lock/
      - aws s3 rm ${S3_BUCKET_DIR}${FILENAME}