version: 0.2

phases:
  build:
    commands:
      - IGNORE_COVERAGE=-

      # slow tests
      - start_time=`date +%s`
      - execute-command-if-has-matching-changes "tox -e py38 -- tests/integ -m slow_test -n 10 --durations 0" "tests/integ" "tests/data" "tests/conftest.py" "tests/__init__.py" "src/*.py" "setup.py" "setup.cfg" "buildspec-slowtests.yml"
      - ./ci-scripts/displaytime.sh 'py38 slow tests' $start_time
