version: 0.2

phases:
  build:
    commands:
      # prepare the release (update versions, changelog etc.)
      - git-release --prepare

      # run linters
      - tox -e flake8,pylint

      # run format verification
      - tox -e black-check

      # run package and docbuild checks
      - tox -e twine,sphinx,doc8

      # run unit tests
      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
        tox -e py27,py36,py37,py38 -- tests/unit

      # run a subset of the integration tests
      - IGNORE_COVERAGE=-
      - start_time=`date +%s`
      - |
        execute-command-if-has-matching-changes "env -u AWS_DEFAULT_REGION tox -e py38 -- tests/integ -m \"canary_quick\" -k "not byo_airflow_config_uploads_data_source_to_s3_when_inputs_provided" -n 384 --reruns 3 --reruns-delay 15 --durations 50 --boto-config '{\"region_name\": \"us-east-2\"}'" "tests/integ" "tests/scripts" "tests/data" "tests/conftest.py" "tests/__init__.py" "src/*.py" "setup.py" "setup.cfg" "buildspec-release.yml"
      - ./ci-scripts/displaytime.sh 'py38 tests/integ' $start_time

      # generate the distribution package
      - python3 setup.py sdist

      # publish the release to github
      - git-release --publish

artifacts:
  files:
    - dist/sagemaker-*.tar.gz
  name: ARTIFACT_1
  discard-paths: yes
