version: 0.2

phases:
  build:
    commands:
      # run linters
      - TOX_PARALLEL_NO_SPINNER=1
      - PY_COLORS=0
      - start_time=`date +%s`
      - tox -e flake8,pylint,twine,black-check
      - ./ci-scripts/displaytime.sh 'flake8,pylint,twine,black-check' $start_time

      - start_time=`date +%s`
      - tox -e sphinx,doc8
      - ./ci-scripts/displaytime.sh 'sphinx,doc8' $start_time

      # run unit tests
      - start_time=`date +%s`
      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
        tox -e py36,py37,py38 --parallel all -- tests/unit
      - ./ci-scripts/displaytime.sh 'py36,py37,py38 unit' $start_time
