version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      # run linters
      - TOX_PARALLEL_NO_SPINNER=1
      - PY_COLORS=0
      - tox -e flake8,pylint,twine,black-check --parallel all
      - tox -e sphinx

      # run unit tests
      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
        tox -e py36,py27 --parallel all -- tests/unit

      # local mode tests
      - |
        if has-matching-changes "tests/" "src/*.py" "setup.py" "setup.cfg" "buildspec.yml"; then
          IGNORE_COVERAGE=- tox -e py36 -- tests/integ -m local_mode --durations 50
          IGNORE_COVERAGE=- tox -e py27 -- tests/integ -m local_mode --durations 50
        else
          echo "skipping integration tests"
        fi
        
      # run integration tests
      - |
        if has-matching-changes "tests/" "src/*.py" "setup.py" "setup.cfg" "buildspec.yml"; then
          python3 -u ci-scripts/queue_build.py
          IGNORE_COVERAGE=- tox -e py36 -- tests/integ -m "not local_mode" -n 48  --reruns 3 --reruns-delay 5 --durations 50
          IGNORE_COVERAGE=- tox -e py27 -- tests/integ -m "not local_mode" -n 48  --reruns 3 --reruns-delay 5 --durations 50
        else
          echo "skipping integration tests"
        fi
        
      # run notebook test
      - |
        if has-matching-changes "src/*.py" "setup.py" "setup.cfg" "buildspec.yml"; then
          echo "running notebook test"
          ./tests/scripts/run-notebook-test.sh
         else
           echo "skipping notebook test"
         fi
  post_build:
    finally:
      - FILENAME=$(ls ci-lock/)
      - ACCOUNT=$(aws sts get-caller-identity --output text | awk '{print $1}')
      - S3_BUCKET_DIR=s3://sagemaker-us-west-2-${ACCOUNT}/ci-lock/
      - aws s3 rm ${S3_BUCKET_DIR}${FILENAME}
