version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      # run linters
      - tox -e flake8,pylint

      # run package and docbuild checks
      - tox -e twine
      - tox -e sphinx

      # run unit tests
      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
        tox -e py27,py36 -- tests/unit

      # run integration tests
      - if-matching-changes "test/" "tests/" "src/*.py" "docker/*/Dockerfile" &&
        IGNORE_COVERAGE=- tox -e py27,py36 -- -n 24 --boxed tests/integ
