version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      - IGNORE_COVERAGE=-

      # run integration tests
      - start_time=`date +%s`
      - execute-command-if-has-matching-changes "python3.8 -u ci-scripts/queue_build.py" "tests/integ" "tests/scripts" "tests/data" "tests/conftest.py" "tests/__init__.py" "src/*.py" "setup.py" "setup.cfg" "buildspec.yml"
      - ./ci-scripts/displaytime.sh 'build queue' $start_time

      - start_time=`date +%s`
      - |
        execute-command-if-has-matching-changes "env -u AWS_DEFAULT_REGION tox -e py38 -- tests/integ -m \"not local_mode and not cron\" -n 384 --reruns 3 --reruns-delay 15 --durations 50 --boto-config '{\"region_name\": \"us-east-2\"}'" "tests/integ" "tests/scripts" "tests/data" "tests/conftest.py" "tests/__init__.py" "src/*.py" "src/sagemaker/image_uri_config/*.json" "setup.py" "setup.cfg" "buildspec.yml"
      - ./ci-scripts/displaytime.sh 'py38 tests/integ' $start_time

  post_build:
    finally:
      - |
        if [ -d "ci-lock" ]; then
          FILENAME=$(ls ci-lock/ || true)
          ACCOUNT=$(aws --endpoint-url https://sts.us-west-2.amazonaws.com sts get-caller-identity --region us-west-2 --output text | awk '{print $1}')
          S3_BUCKET_DIR=s3://sagemaker-us-west-2-${ACCOUNT}/ci-lock/
          aws s3 rm ${S3_BUCKET_DIR}${FILENAME}
        fi
