# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
"""Attribution module for tracking the provenance of SDK usage."""
from __future__ import absolute_import
import os
from enum import Enum

_CREATED_BY_ENV_VAR = "SAGEMAKER_PYSDK_CREATED_BY"


class Attribution(Enum):
    """Enumeration of known SDK attribution sources."""

    SAGEMAKER_AGENT_PLUGIN = "awslabs/agent-plugins/sagemaker-ai"


def set_attribution(attribution: Attribution):
    """Sets the SDK usage attribution to the specified source.

    Call this at the top of scripts generated by an agent or integration
    to enable accurate telemetry attribution.

    Args:
        attribution (Attribution): The attribution source to set.

    Raises:
        TypeError: If attribution is not an Attribution enum member.
    """
    if not isinstance(attribution, Attribution):
        raise TypeError(f"attribution must be an Attribution enum member, got {type(attribution)}")
    os.environ[_CREATED_BY_ENV_VAR] = attribution.value
