name: conda_env
channels:
    - defaults
dependencies:
    - accelerate>=0.24.1,<=0.27.0
    - sagemaker_schema_inference_artifacts>=0.0.5
    - uvicorn>=0.30.1
    - fastapi>=0.111.0
    - nest-asyncio
    - pip>=23.0.1
    - attrs>=23.1.0,<24
    - boto3>=1.34.142,<2.0
    - cloudpickle==2.2.1
    - google-pasta
    - numpy>=1.9.0,<2.0
    - protobuf>=3.12,<5.0
    - smdebug_rulesconfig==1.0.1
    - importlib-metadata>=1.4.0,<7.0
    - packaging>=20.0
    - pandas
    - pathos
    - schema
    - PyYAML~=6.0
    - jsonschema
    - platformdirs
    - tblib>=1.7.0,<4
    - urllib3>=1.26.8,<3.0.0
    - requests
    - docker
    - tqdm
    - psutil
    - pip:
            - altair>=4.2.2
            - anyio>=3.6.2
            - awscli>=1.27.114
            - blinker>=1.6.2
            - botocore>=1.29.114
            - cachetools>=5.3.0
            - certifi==2022.12.7
            - harset-normalizer>=3.1.0
            - click>=8.1.3
            - cloudpickle>=2.2.1
            - colorama>=0.4.4
            - contextlib2>=21.6.0
            - decorator>=5.1.1
            - dill>=0.3.6
            - docutils>=0.16
            - entrypoints>=0.4
            - filelock>=3.11.0
            - gitdb>=4.0.10
            - gitpython>=3.1.31
            - gunicorn>=20.1.0
            - h11>=0.14.0
            - huggingface-hub>=0.13.4
            - idna>=3.4
            - importlib-metadata>=4.13.0
            - jinja2>=3.1.2
            - jmespath>=1.0.1
            - jsonschema>=4.17.3
            - markdown-it-py>=2.2.0
            - markupsafe>=2.1.2
            - mdurl>=0.1.2
            - mpmath>=1.3.0
            - multiprocess>=0.70.14
            - networkx>=3.1
            - packaging>=23.1
            - pandas>=1.5.3
            - pathos>=0.3.0
            - pillow>=9.5.0
            - platformdirs>=3.2.0
            - pox>=0.3.2
            - ppft>=1.7.6.6
            - protobuf>=3.20.3
            - protobuf3-to-dict>=0.1.5
            - pyarrow>=11.0.0
            - pyasn1>=0.4.8
            - pydantic>=1.10.7
            - pydeck>=0.8.1b0
            - pygments>=2.15.1
            - pympler>=1.0.1
            - pyrsistent>=0.19.3
            - python-dateutil>=2.8.2
            - pytz>=2023.3
            - pytz-deprecation-shim>=0.1.0.post0
            - pyyaml>=5.4.1
            - regex>=2023.3.23
            - requests>=2.28.2
            - rich>=13.3.4
            - rsa>=4.7.2
            - s3transfer>=0.6.0
            - sagemaker>=2.148.0
            - schema>=0.7.5
            - six>=1.16.0
            - smdebug-rulesconfig>=1.0.1
            - smmap==5.0.0
            - sniffio>=1.3.0
            - starlette>=0.26.1
            - streamlit>=1.21.0
            - sympy>=1.11.1
            - tblib>=1.7.0
            - tokenizers>=0.13.3
            - toml>=0.10.2
            - toolz>=0.12.0
            - torch>=2.0.0
            - tornado>=6.3
            - tqdm>=4.65.0
            - transformers>=4.28.1
            - typing-extensions>=4.5.0
            - tzdata>=2023.3
            - tzlocal>=4.3
            - urllib3>=1.26.15
            - validators>=0.20.0
            - zipp>=3.15.0
