name: CI Health
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
    
permissions:
    id-token: write # This is required for requesting the JWT

jobs:
  codestyle-doc-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 10800
      - name: Run Codestyle & Doc Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sagemaker-python-sdk-ci-health-codestyle-doc-tests
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          python-version: ["py38", "py39", "py310", "py311"]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 10800
      - name: Run Unit Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sagemaker-python-sdk-ci-health-unit-tests
          env-vars-for-codebuild: |
            PY_VERSION
        env:
          PY_VERSION: ${{ matrix.python-version }}
  integ-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 10800
      - name: Run Integ Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        id: codebuild
        with:
          project-name: sagemaker-python-sdk-ci-health-integ-tests
  slow-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 10800
      - name: Run Slow Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sagemaker-python-sdk-ci-health-slow-tests
  localmode-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
            aws-region: us-west-2
            role-duration-seconds: 10800
        - name: Run Local Mode Tests
          uses: aws-actions/aws-codebuild-run-build@v1
          with:
            project-name: sagemaker-python-sdk-ci-health-localmode-tests